name: Package

on: 
  push:
    branches:
    - master
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build solution
      run: dotnet build --configuration Release --no-restore
    - name: Run Unit Tests
      run: dotnet test 
    - name: Pack nuget Package
      run: dotnet pack --configuration Release
    - name: Push package to nuget
      run: dotnet nuget push **/*.nupkg
          --api-key ${{ secrets.NUGET_CRX_DEPLOY_KEY }}
          --source https://api.nuget.org/v3/index.json
          --skip-duplicate --no-symbols true
      #run: dotnet nuget push "bin/Release/CRX.Extensions.1.0.2.nupkg" --source "github"
            
